### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by PRosenstatter** [3ahmns-WiSem-2223/01lbrandstaetter-fingeruebung-eindimensionalesArray#1]
Sehr geehrter Herr Brandstätter,

ich habe mir Ihr Projekt genauer unter die Lupe genommen und sind ihre ungenützten Namespaces ins Auge gestochen. Ich würde Ihnen herzlichst empfehlen diese zu entfernen.

Mit freundlichen Grüßen 
Rosenstatter Paul

**Comment by lbrandstaetter** [comment]
Sehr geehrter Herr Rosenstatter, ich habe mir ihr issue durchgelesen und  sehr zu herzen genommen. Ich habe es schleunigst behoben. Vielen Dank für ihre aufmerksamkeit beim durchlesen des Skirpts
Lg Brandstätter Luca
